services:
  - type: web
    name: vendas-orcamentos
    runtime: node
    plan: free
    region: oregon
    rootDir: vendas-orcamentos
    buildCommand: npm install
    startCommand: npm run db:migrate && npm run db:seed && npm start
